### ISSUE TITLE
安装过程出现错误

### ISSUE THREAD

**Issue by hluler** [cobub/razor#11]
Table 'minichaoshi.razor_users' doesn't exist

INSERT INTO `razor_users` (`username`, `password`, `email`, `last_ip`, `new_email_key`, `created`, `activated`) VALUES ('test', '$P$BM5Cu/QFLcI1YctMOrE2yeO2FDw/TZ0', '3449376@qq.com', '222.95.57.111', 'ae2be2ea61117c78bc0eedc9db328efc', '2012-08-30 21:04:50', 0)

Filename: ..\wwwroot\system\database\DB_driver.php

Line Number: 330

**Comment by ljie-PI** [comment]
Many tables are created except **razor_users**
