### ISSUE TITLE
Page view visit path always show "no data"

### ISSUE THREAD

**Issue by jdsalat** [cobub/razor#110]
Hi 
i have included cobub razor SDK in my application it is working fine accept pageview & path report, it always displays "no data". the table below this graph shows the data for activity. there is data in dim_activity table also.

i have executed query given here.
https://github.com/cobub/razor/issues/23

but no solution found please help me why it is not working

**Comment by cobub** [comment]
The data is calculated in rundaily sp, so it will be shown in next day.
