### ISSUE TITLE
苹果版SDK统计的使用时长

### ISSUE THREAD

**Issue by qac2013** [cobub/razor#111]
请教个问题，安装最新版的cobub，跑了一段时间的数据，发现使用时长数据些问题：

总用户数安卓是苹果2.5倍多，不清楚那个机制引起的使用时长数据相差这么多？
          0-3                3-10                30
苹果版	31(1.7%)      294(15.9%)     741(40%)
安卓版	176(9.4%)	   381(20.4%)     7(0.4%)

**Comment by cobub** [comment]
fixed
