### ISSUE TITLE
SaveInfo中的文件句柄打开未关闭

### ISSUE THREAD

**Issue by xuwenq** [cobub/razor#122]
如
FileInputStream in = new FileInputStream(Environment.getExternalStorageDirectory().getAbsolutePath()+"/mobclick_agent_cached_"+context.getPackageName());
等，没有显示调用close代码；
另外
Environment.getExternalStorageDirectory().getAbsolutePath()+"/mobclick_agent_cached_"+context.getPackageName()
这种拼接多次出现，不能用一个变量替代一下？

**Comment by cobub** [comment]
This has been fixed.
