### ISSUE TITLE
MyCrashHandler保存bug

### ISSUE THREAD

**Issue by xuwenq** [cobub/razor#123]
android.os.Process.killProcess(android.os.Process.myPid());
可能在
UmsAgent.saveInfoToFile("errorInfo", errorInfo, context);
之前就执行了，导致错误日志无法写入文件

**Comment by wy353208214** [comment]
这个太坑了，啥时候修复啊，，害我找了好久啊。
建议同步写到文件里面，写完后再kill-process

**Comment by cobub** [comment]
It has been fixed.
