### ISSUE TITLE
Online Users By Area

### ISSUE THREAD

**Issue by maneeshdisodia** [cobub/razor#133]
hii cocub,
all analytics are working fine for me except
in console "online user" when we query about "Online Users By Area" this only show country ...in depth details are keep on loading and not showing any result(schedule are working fine)

Thanks

**Comment by cobub** [comment]
The href attribute of EasyUI panel uses Get as default method, and add &_=xxx behind CI url, this makes  CI can not parse the url. Now  it has been changed to POST method.
