### ISSUE TITLE
本地server建立起来了，SDK也用起来了，但是server收不到消息

### ISSUE THREAD

**Issue by poople** [cobub/razor#134]
我的server的框架式，win64+Apache+mysql+PHP，然后按照步骤也把相关server配置起来了，本地方访问也是可以的（本地访问http://localhost/razor/web/index.php，访问http://localhost/razor/web/是不行的，也就是PHP中$config['index_page'] = 'index.php?';是不管用的）
但是为什么本地的android的模拟器，访问就不行，这就导致我server根本收不到消息啊
一直提示web page not available
这个和权限有关系吗？
这是第一次搞PHP的啊

**Comment by ShaunSheep** [comment]
1. cmd—>ipconfig  记下ipv4地址

发起请求的时候，将localhost 替换为 你的ipv4 地址、

2.在web端项目里的config文件，重新配置你之前设置的超级域名——将localhost替换为ipv4地址

这样，才能保证手机能通过wifi网络访问你pc电脑起的apche服务器
