### ISSUE TITLE
Cobub Razor not populating data

### ISSUE THREAD

**Issue by panjigautama** [cobub/razor#139]
Hi Everyone,

I already setup cobub razor & cron tab, and use the android SDK. Data is uploaded to database ( i checked it on the database ). However it seems the data is not populated into analytics. I try to call archiveHourly - archiveWeekly - archiveMonthly - archiveLaterData - archiveUsingLog manually but it seems it now showing anything.

![screen shot 2014-09-19 at 4 01 47 am](https://cloud.githubusercontent.com/assets/3119362/4327274/7d61f8cc-3f77-11e4-9a7f-ecfe5d04736a.png)

**Comment by hnabtiti** [comment]
me too  what is the problem

**Comment by brucenan** [comment]
archiveHourly is always run rundim(), runfact() and runsum() store procedure, maybe something wrong when run these SPs, so you can try to run them manually, and try to find some error info/

**Comment by cobub** [comment]
fixed
