### ISSUE TITLE
我在代码里发现了这个ASIdentifierManager这个会引起苹果审核拒掉app么

### ISSUE THREAD

**Issue by yupliang** [cobub/razor#145]
+(NSString *)getUMSUDID
{
    NSString \* udidInKeyChain = [SFHFKeychainUtils getPasswordForUsername:@"UMSAgentUDID" andServiceName:@"UMSAgent" error:nil];
    if(udidInKeyChain && ![udidInKeyChain isEqualToString:@""])
    {
        return udidInKeyChain;
    }
    else
    {
        NSString *idfa = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString];
        if(idfa && ![idfa isEqualToString:@""])
        {
            [SFHFKeychainUtils storeUsername:@"UMSAgentUDID" andPassword:idfa forServiceName:@"UMSAgent" updateExisting:NO error:nil];
            return idfa;
        }
        else
        {
            NSString *openUDID = [UMS_OpenUDID value];
            [SFHFKeychainUtils storeUsername:@"UMSAgentUDID" andPassword:openUDID forServiceName:@"UMSAgent" updateExisting:NO error:nil];
            return openUDID;
        }
    }
}

**Comment by cobub** [comment]
If there're ads in your app, it should be OK. If not, you can remove the codes using ASIdentifierManager.

**Comment by yesiya** [comment]
do you mean delete this part directly ？

NSString *idfa = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString];
if(idfa && ![idfa isEqualToString:@""])
{
[SFHFKeychainUtils storeUsername:@"UMSAgentUDID" andPassword:idfa forServiceName:@"UMSAgent" updateExisting:NO error:nil];
return idfa;
}

**Comment by cobub** [comment]
please refer to the latest code.
