### ISSUE TITLE
网站没有任何新数据显示

### ISSUE THREAD

**Issue by zzturi** [cobub/razor#79]
数据库有内容，网站没有任何新数据显示，定时任务也执行正确了。一天内，网站所有数据都是初始无数据或0的。

**Comment by HippolyteSagittaHU** [comment]
在CentOS中, sh文件里的命令, 需要把php写全路径, 才会执行成功, 请大家试试

**Comment by HippolyteSagittaHU** [comment]
关于时区设置, 我看application/config/config.php 中的数据如下
$config['time_reference'] = 'local';
$config['timezones'] = 'UTC';

我把local修改为gmt, 或者修改"timezones"为 'UTC +8:00', 在执行计划任务重的命令, 数据都还是UTC的时间, 最后我直接用 date('Y-m-d H:i:s') 的方式来获得当前时间, 而不去使用"timezones", 同时程序中的时间函数也有一个地方写错了, 'Y-m-d H:i:m', 把最后一个m修改为s就正确了, controllers/archive.php 中有多个地方都有这个错误, 替换一下就ok了
